collections:
  sections:
    output: true

defaults:
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
